project:
  type: book

book:
  title: "Data7 Exploratory Data Analysis In Python Book"
  author: "Greg Chism"
  cover-image: images/cover.png
  chapters:
    - index.qmd
    - intro.qmd
    - DiagnosingLikeDataDoctor.qmd
    - ExploringLikeDataAdventurer.qmd
    - TransformingLikeDataTrans.qmd
    - ImputingLikeDataScientist.qmd
    - CorrelateLikeDataMaster.qmd


  repo-url: https://github.com/Gchism94/EDA_In_Python_Book

bibliography: references.bib

format:
  html:
    theme: cosmo
    code-copy: true



